### ISSUE TITLE
add Adobe Illustrator support

### ISSUE THREAD

**Issue by haysclark** [theasci/extendscript-repl#3]
Technically, one could use `-./run.rb --app=photoshop` assuming the fix from PR #1 is used; however, it would be nice to have an 'illustrator' flag support.

**Comment by josejardon** [comment]
Added [here](https://github.com/theasci/extendscript-repl/pull/4)

**Comment by haysclark** [comment]
@josejardon Looks like the repo still needs to be [published](https://github.com/theasci/extendscript-repl#npm-release-tasks) to _npm_. 😉

**Comment by josejardon** [comment]
> @josejardon Looks like the repo still needs to be [published](https://github.com/theasci/extendscript-repl#npm-release-tasks) to _npm_. 😉

The new version has been published, thanks for reminding me! 👍
